http-bridge = "http://localhost:8080/"
#Port to listen to requests
port = 3000
network = "mainnet"
#The refresh interval in milliseconds
refresh-interval = 1000
#The sqlite database
database = "transactions.db"
